-- Create the Messages table
create table public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null,
  original_language text not null default 'en',
  user_name text not null,
  translations jsonb default '{}'::jsonb
);

-- Create the Documents table (for the editor)
create table public.documents (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null default 'Untitled',
  content text not null,
  translations jsonb default '{}'::jsonb,
  last_updated_by text
);

-- Enable Realtime
alter publication supabase_realtime add table messages;
alter publication supabase_realtime add table documents;
